services:
  - type: web
    name: flavors-feast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      gunicorn icode.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-u+vy*8$my@o4vdb6-i#*&a495r089ws#nzres%7u@yc!!sjv*(
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
