services:
  - type: web
    name: flavors-feast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && gunicorn icode.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
