# Generated by Django 5.0.7 on 2024-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('massage', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
