# Generated by Django 5.0.7 on 2024-08-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icode_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Fname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Lname',
            new_name='Queries',
        ),
    ]
