# Generated by Django 5.0.7 on 2024-08-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icode_app', '0002_rename_fname_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='Massage',
        ),
    ]
