# Generated by Django 5.0.7 on 2024-08-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icode_app', '0003_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Massage',
            new_name='Lname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='massage',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Queries',
            new_name='phone',
        ),
    ]
