# Generated by Django 5.0.7 on 2024-08-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icode_app', '0004_rename_email_contact_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Lname',
        ),
    ]
