# Generated by Django 5.0.7 on 2024-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icode_app', '0005_remove_contact_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Queries',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
