# Generated by Django 5.0.7 on 2024-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icode_app', '0006_contact_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Queries',
            field=models.CharField(max_length=100),
        ),
    ]
