# Generated by Django 5.0.7 on 2024-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icode_app', '0007_alter_contact_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party_size', models.CharField(max_length=100)),
                ('Reservation_Date', models.CharField(max_length=100)),
                ('Reservation_Time', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('Special_Request', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
